services:
  catalog:
    build:
      context: ./catalog
    container_name: easypass-catalog
    hostname: catalog
    ports:
      - "8001:8000"
    networks:
      - easypass-network

  ticketing:
    build:
      context: ./ticketing
    container_name: easypass-ticketing
    hostname: ticketing
    
    ports:
      - "8002:8000"
    environment:
      CATALOG_SERVICE_URL: http://catalog:8000
    depends_on:
      - catalog
    networks:
      - easypass-network

  access_control:
    build:
      context: ./access_control
    container_name: easypass-access-control
    hostname: access_control
    
    ports:
      - "8003:8000"
    environment:
      TICKETING_SERVICE_URL: http://ticketing:8000
    depends_on:
      - ticketing
    networks:
      - easypass-network

networks:
  easypass-network:
    driver: bridge